### PR TITLE
multiChoice: scroll list if len(options) > term.height

### PR DESCRIPTION
**Pull request by chessman**
Closes: https://github.com/abiosoft/ishell/issues/35

I've implemented options scrolling. There is no need in `update()` every 200 ms anymore. Now we do it only on terminal resizeing.

### CODE REVIEW

**Comment by abiosoft** [comment]
Wow. Thanks. 👏

**Comment by abiosoft** [comment]
There is only one problem I noticed. After selection, the next output is on same line as the last option.
```
What are your favourite programming languages ?
  ✓ Python
  ✓ Go
 ❯✓ Haskell
  ✓ RustYour choices are Python, Go, Haskell, Rust
```

**Comment by chessman** [comment]
Yes, probably `s/Print/Println/` on line 504. I will fix it tomorrow.

**Comment by abiosoft** [comment]
This is better than what we currently have and fixes #35. So I'll be merging it in.

However, I'd still like to explore the possibility of not clearing the screen if len(options) < term.height.

**Comment by chessman** [comment]
Yes, that's possible even when len(options) > term.height. We need to fix maximum number of options per page like Inquirer.js does.

**Comment by ahmetb** [comment]
I know @abiosoft is expert at this but I've been meaning to port Inquirer.js as is to Go for a while, until I discovered this project. 

My 2c: we shoukd create a new project that copies Inquirer.js in Go (they've got good UX, multi platform support, fancy chars etc) and use it in ishell. Having a separate project with solid logic to handle corner cases such as this would be a 💯👌.

**Comment by abiosoft** [comment]
Good point @ahmetb. I am giving it strong consideration. I'll notify when I start something.

Thanks.

**Pull request merged**
