### PR TITLE
Adds readline integration

### PR DESCRIPTION
**Pull request by dokipen**

### CODE REVIEW

**Comment by abiosoft** [comment]
I realised that readline uses cgo which can affect portability and I am not sure if readline works on Windows.

**Comment by dokipen** [comment]
If I re-implement with this would you take it?

https://github.com/chzyer/readline

**Comment by abiosoft** [comment]
Yeah. That looks better :smile:

**Comment by dokipen** [comment]
Opening new pull request with go-readline.

**Pull request closed without merging**
