### PR TITLE
Added rootCmd accessor to the shell

### PR DESCRIPTION
**Pull request by ugy**
As mentionned in #97, I work around your code to have accessors on the shell's root command.

### CODE REVIEW

**Comment by abiosoft** [comment]
Does this fix your issue?

**Comment by ugy** [comment]
Yes, now both my custom completer and the shell's handleCommand use the same root command :)

**Comment by abiosoft** [comment]
Is your code publicly available, I'd like to have a look at the snippet if possible to get a better understanding. 
This works but I feel this may be done cleaner than simply replacing `rootCmd`. Or there could be a bug somewhere.

**Comment by ugy** [comment]
My code is not public but I can write something for you tomorrow so you'll understand better my problem.

I found the problem was that my custom completer and the shell's handleCommand wouldn't use the same command, in your shell's initCompleter, you set the completer's cmd attribute to the shell's rootCmd, in this case everything works fine as the completer.Do function and the shell's handleCommand will use the same command.

But when I create my custom completer, I have to set the cmd's attribute to a new command I create as I don't have public access to the shell's rootCmd. In this case, the shell's completion will use my newly created command, but the shell's handleCommand will still use it's own command created in the function NewWithConfig, so the completion will work, but when I hit enter it won't find my command.

I hope it helps, anyway I'll write some code tomorrow if you need.

**Comment by abiosoft** [comment]
No worries. Do you mind adding an additional line of comment to `SetRootCmd` that kinda cautions the user. Something like the following.
```
// Use with caution, this may affect the behaviour of the default completer. 
```

Also, I'd prefer renaming `GetRootCmd()` to simply `RootCmd()`.

**Comment by ugy** [comment]
Alright !
I have the snippet of code you wanted :)

```package main

import (
	"strings"

	"github.com/abiosoft/ishell"
	shlex "github.com/flynn-archive/go-shlex"
)

type customCompleter struct {
	cmd *ishell.Cmd
}

func (c customCompleter) Do(line []rune, pos int) (newLine [][]rune, length int) {
	var words []string
	if w, err := shlex.Split(string(line)); err == nil {
		words = w
	} else {
		// fall back
		words = strings.Fields(string(line))
	}

	var cWords []string
	prefix := ""
	if len(words) > 0 && pos > 0 && line[pos-1] != ' ' {
		prefix = words[len(words)-1]
		cWords = c.getWords(words[:len(words)-1])
	} else {
		cWords = c.getWords(words)
	}

	var suggestions [][]rune
	for _, w := range cWords {
		if strings.HasPrefix(w, prefix) {
			suggestions = append(suggestions, []rune(strings.TrimPrefix(w, prefix)))
		}
	}
	if len(suggestions) == 1 && prefix != "" && string(suggestions[0]) == "" {
		suggestions = [][]rune{[]rune(" ")}
	}
	return suggestions, len(prefix)
}

func (c customCompleter) getWords(w []string) (s []string) {
	cmd, args := c.cmd.FindCmd(w)
	if cmd == nil {
		cmd, args = c.cmd, w
	}
	if cmd.Completer != nil {
		return cmd.Completer(args)
	}
	for _, child := range cmd.Children() {
		s = append(s, child.Name)
	}
	return
}

func main() {
	shell := ishell.New()

	completerCmd := ishell.Cmd{}
	completerCmd.AddCmd(&ishell.Cmd{
		Name: "test",
		Help: "Test function",
		Func: func(c *ishell.Context) {
			c.Print("this is a test function")
		},
	})
	completer := customCompleter{cmd: &completerCmd}

	shell.CustomCompleter(completer)
	shell.Run()
	shell.Close()
	shell.Wait()
}
```

I just copy pasted your completer to keep it simple. if you test it, you'll see it will complete `test`, but will fail to run it as doesn't exists in the shell.rootCmd used by Shell.handleCommand.

While I'm here, there are several problems I encountered while trying to code my custom completer that I wanted to discuss with you.

Firstly, someone writing a custom completer can not disable it when MultiChoice is called as Shell.multiChoiceActive is private, you're using this attribute in your completer's disabled function to know when not to do the completion.
```
func (ic iCompleter) Do(line []rune, pos int) (newLine [][]rune, length int) {
	if ic.disabled != nil && ic.disabled() {
		return nil, len(line)
	}
```
ic.disabled being defined here:
```
func (s *Shell) initCompleters() {
	s.setCompleter(iCompleter{cmd: s.rootCmd, disabled: func() bool { return s.multiChoiceActive }})
}
```
One possible solution would be to create a accessor for Shell.multiChoiceActive, or make it a public attribute.

Secondly, iCompleter.Do will drop the prefix in the words list you're giving to iCompleter.getWords function:
```
var cWords []string
	prefix := ""
	if len(words) > 0 && pos > 0 && line[pos-1] != ' ' {
		prefix = words[len(words)-1]
		cWords = ic.getWords(words[:len(words)-1])
	} else {
		cWords = ic.getWords(words)
	}
```
Because of that, someone using a custom completer cannot really "complete" a word, he can just returns the list of all possibilities that will be filtered by the prefix in iCompleter.Do function.
In my case this is a problem as I intended to use a custom completer to complete paths.
To be clearer, imagine you want to write a change directory function that complete paths, how can you know you're completing a folder, sub-folder, sub-sub-folder, etc ? Because the prefix is dropped from the list of words, I cannot know if the user entered:
- `cd fold`
- `cd folder/sub`
- `cd folder/subfolder/sub`
In all cases, I will receive en empty string slice in my custom completer function, so I would have to return all possible paths, for all folders and sub folders, recursively to be able to complete a path.

There are several possible solution for that too, passing the prefix as an argument, not dropping the prefix but possibly changing more code ...

Thirdly, it would be nice to have the writer and reader of the shell accessible, sometimes I want to write data to the shell from a streamed, buffered source and I have to read all the content, then call ishell.Context.Print to display it, where I could use buffer.WriteTo(shell.writer).

I hope I'm not being to demanding, your project is great and I'd like to contribute to it, those are specific problems encountered while using your module and I'd love to help if you feel like it needs modification,
I can create several issues if you want, and later, pull requests if it helps :)

By the way, I made the changes you asked for for the rootCmd accessor and pushed it.

Have a good day !

**Pull request merged**
