### PR TITLE
add Checklist

### PR DESCRIPTION
**Pull request by chessman**
Hello. I implemented a new mode for multiple selection. Checklist is similar to MultiChoice but user can choose multiple variants using Space.

It is a straightforward implementation so any improvements are appreciated. For example, `return []int{-1}` looks like hack. I think, it would be convinient to return `(int, error)` from `MultiChoice` and `([]int, error)` from Checklist but it will break API.

### CODE REVIEW

**Comment by abiosoft** [comment]
I don't mind it breaking the API at the moment. Multichoice was just implemented so there can not be many users yet.

But what are error options in multichoice and checklist other than `Ctrl-c` and `Ctrl-d` ?

**Comment by abiosoft** [comment]
And thanks again.

**Comment by abiosoft** [comment]
For checklist, it is perfectly fine to return an empty slice when nothing is selected. I do not see anything wrong with that.

**Comment by chessman** [comment]
I think it is `Ctrl-c` and `Ctrl-d` only. But with current API I should write the following code after every call:
```
	choice := s.Checklist(options, text, init)
	if len(choice) > 0 && choice[0] == -1 {
		return nil, readline.ErrInterrupt
	}
```

**Comment by chessman** [comment]
And I should distinguish empty checklist and `Ctrl-c` as well. Because when user didn't choose anything I want to show checklist again.

**Comment by abiosoft** [comment]
Thanks. I'll merge it in and cleanup afterwards.

**Comment by chessman** [comment]
Thank you!

**Comment by abiosoft** [comment]
Haha race condition comments.

**Pull request merged**
